test_check_login:
  url: "https://magento.softwaretestingboard.com/customer/account/login/"
  username: "dheerajjain60@gmail.com"
  password: "Jan@2012"
  expected: "https://magento.softwaretestingboard.com/"